# Generated by Django 5.2.1 on 2025-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Attendance', 'Attendance'), ('no show', 'no show'), ('Cancelled by Staff', 'Cancelled by Staff')], default='Pending', max_length=30),
        ),
    ]
